name: Add the Last 5 Blog Post in the README.md file

on:
   schedule:
     - cron: '0 * * * *'
    workflow_dispatch:

jobs:
  update-readme-with-blog:
  name: 'Update the Profile description with the last 5 post on my blog'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: gautamkrishnar/blog-post-workflow@master
      with:
        max_post_count: "5"
        feed_list: "https://ricardoleal20.github.io/Blog/index.xml"